### ISSUE TITLE
Not pulling stats from lemmy.fan

### ISSUE THREAD

**Issue by citking** [LemmyNet/lemmy-stats-crawler#17]
Not pulling api stats from real.lemmy.fan despite federation being enabled and site being public. Original issue opened at https://github.com/maltfield/awesome-lemmy-instances/issues/44 and I was referred here.

**Comment by Nutomic** [comment]
I cant reproduce this, maybe it was just a temporary problem? And the federation issues in 0.19 wont prevent crawling in any way.

```
cargo run -- --start-instances real.lemmy.fan --max-crawl-distance 0 -v 4
Finished dev [unoptimized] target(s) in 0.12s
Running `target/debug/lemmy-stats-crawler --start-instances real.lemmy.fan --max-crawl-distance 0 -v 4`
Crawling...
DEBUG - Worker 1 starting job real.lemmy.fan at distance 0
Crawl complete, took 1s
Number of Lemmy instances: 1
Total users: 29
Half year active users: 17
Monthly active users: 13
Weekly active users: 5
Daily active users: 1

Use --json flag to get machine readable output
```

cc @maltfield

**Comment by maltfield** [comment]
I guess the real test would be to `--start-instances` from some distinct instance and see if the instance in question is found

**Comment by maltfield** [comment]
@Nutomic not sure if you'd consider this a bug, since it appears that domains that redirect to the same lemmy instance are returned by `lemmy-stats-crawler` more than once

possibly related https://github.com/LemmyNet/lemmy-stats-crawler/pull/11

**Comment by Nutomic** [comment]
Thats not a redirect but two subdomains returning the exact same data. Seems like a rather weird setup because federation goes through real.lemmy.fan, while images are hosted on lemmy.fan. Anyway I added a check that the domain is the expected one, which fixes this.
