### ISSUE TITLE
Duplicate Instances in Output

### ISSUE THREAD

**Issue by maltfield** [LemmyNet/lemmy-stats-crawler#8]
I think we should update this repo so that -- if the crawl finds two servers that are actually the same -- it omits the one that redirects to the other.

I noticed that one Lemmy Instance that changed its name and started redirecting the old one to the new one is showing-up twice in [awesome-lemmy-instances](https://github.com/maltfield/awesome-lemmy-instances)
1. https://lemmy.burger.rodeo/
1. https://burggit.moe

The first one no longer exists; it just redirects to the second one

```
user@host:~$ curl -I https://lemmy.burger.rodeo
HTTP/2 302 
alt-svc: h3=":443"; ma=2592000
location: https://burggit.moe/
permissions-policy: interest-cohort=()
server: Caddy
strict-transport-security: max-age=31536000;
x-content-type-options: nosniff
date: Tue, 13 Jun 2023 05:14:43 GMT

user@host:~$
```

But `lemmy-stats-crawler` will output the server's stats twice, which obviously throws-off the stats.

## Solution

I guess the solution would be to check if the response code of the API query is a 301 or 302 redirect.

If [a] the response code is a redirect AND [b] the domain that it redirects-to is already another instance in the set of crawled instances, then omit the one that redirects from the output of `lemmy-stats-crawler`

**Comment by Nutomic** [comment]
It should be enough to stop following redirects in general.
